language: node_js
node js:
- lts/*
install:
- yarn install # npm ci
script:
- yarn docs:build # npm run docs:build
- yarn cname
deploy:
  provider: pages
  skip_cleanup: true
  local dir: docs/.vuepress/dist
  glthub.token: $GITHUB_TOKEN #  GitHub 中生成，用于允 Travis 南的济代码，在 Travis 的项目没黑页面涨行配置，没置为 secure varioble
  keep_history: true
  on:
    branch: master